### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by BilalAlpaslan** [ofsenyayla/market-app#1]
çok güzel olmuş birkaç önerim var.
1-Dockerfile da reload ı açık bırakmışsın boş boşuna Watchgod için kaynak harcanıyor docker içerisinde buna ihtiyacın yok
2- bazı ortam değişkenleri var db configleri gibi bunlar için .env dosyası kullanabilirsin
3- docker_commands.txt dosyası yerine scripts diye bir klasör açıp orda tek satırda olsa bash script  yazabilirsin  
4- schemaları yine pydantic modelleri olarak da yazabilirsin ve api.route larına response bu modelleri verip openapi da gözükmelerini sağlayabilirsin
5 pycache ler vb için bir gitignore iyi olurdu

**Comment by ofsenyayla** [comment]
Feedback için teşekkür ederim
